name: teran
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.8.1=py36_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - cffi=1.13.2=py36h2e261b9_0
  - cudatoolkit=10.0.130=0
  - freetype=2.9.1=h8a8886c_1
  - grpcio=1.16.1=py36hf8bcb03_1
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - markdown=3.1.1=py36_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.17.4=py36hc1035e2_0
  - numpy-base=1.17.4=py36hde5b4d6_0
  - olefile=0.46=py_0
  - openssl=1.1.1d=h7b6447c_4
  - pillow=6.2.1=py36h34e0f95_0
  - pip=19.3.1=py36_0
  - protobuf=3.11.2=py36he6710b0_0
  - pycparser=2.19=py_0
  - python=3.6.9=h265db76_0
  - readline=7.0=h7b6447c_5
  - setuptools=42.0.2=py36_0
  - six=1.13.0=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tk=8.6.8=hbc83047_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.3.1=py3.6_cuda10.0.130_cudnn7.6.3_0
  - torchvision=0.4.2=py36_cu100
  - pip:
    - astor==0.8.1
    - atomicwrites==1.2.1
    - attrs==19.3.0
    - awscli==1.16.180
    - backcall==0.1.0
    - bleach==3.1.0
    - boto3==1.10.46
    - botocore==1.13.46
    - cachetools==3.1.1
    - chardet==3.0.4
    - click==7.0
    - colorama==0.4.1
    - cupy-cuda100==6.1.0
    - cycler==0.10.0
    - cython==0.29.10
    - decorator==4.4.1
    - defusedxml==0.6.0
    - dgl==0.1.3
    - dill==0.3.1.1
    - docopt==0.6.2
    - docutils==0.15.2
    - dominate==2.4.0
    - easydict==1.9
    - entrypoints==0.3
    - fastrlock==0.4
    - filelock==3.0.10
    - fire==0.1.3
    - flatbuffers==1.10
    - funcsigs==1.0.2
    - gast==0.3.2
    - google-auth==1.7.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - hunspell==0.5.5
    - idna==2.8
    - imageio==2.6.1
    - imdirect==0.5.0
    - imgaug==0.3.0
    - importlib-metadata==0.23
    - ipykernel==5.1.3
    - ipython==7.9.0
    - ipython-genutils==0.2.0
    - isodate==0.6.0
    - jedi==0.15.1
    - jinja2==2.10.3
    - jmespath==0.9.4
    - joblib==0.14.1
    - json5==0.8.5
    - jsonschema==3.1.1
    - jupyter-client==5.3.4
    - jupyter-core==4.6.1
    - jupyterlab==1.2.1
    - jupyterlab-server==1.0.6
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mistune==0.8.4
    - more-itertools==7.2.0
    - nbconvert==5.6.1
    - nbformat==4.4.0
    - networkx==2.4
    - nltk==3.4.5
    - notebook==6.0.1
    - oauthlib==3.1.0
    - opencv-python==4.1.1.26
    - pandas==0.24.1
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - piexif==1.1.3
    - pipreqs==0.4.10
    - pluggy==0.8.0
    - progressbar==2.5
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - ptyprocess==0.6.0
    - pudb==2019.1
    - py==1.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.7
    - pycocotools==2.0.0
    - pygments==2.4.2
    - pyparsing==2.4.5
    - pyrsistent==0.15.5
    - pytest==4.1.0
    - python-dateutil==2.8.1
    - pytorch-nlp==0.3.7.post1
    - pytorch-warmup==0.0.4
    - pytz==2018.9
    - pywavelets==1.1.1
    - pyyaml==5.3
    - pyzmq==18.1.0
    - ray==0.6.1
    - rdflib==4.2.2
    - redis==3.0.1
    - regex==2019.12.20
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rouge-score==0.0.3
    - rsa==4.0
    - s3transfer==0.2.1
    - sacremoses==0.0.35
    - scikit-image==0.16.2
    - scipy==1.4.1
    - send2trash==1.5.0
    - sentencepiece==0.1.85
    - shapely==1.6.4.post2
    - sklearn==0.0
    - tensorboard-logger==0.1.0
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu==1.14.0
    - termcolor==1.1.0
    - terminado==0.8.2
    - testpath==0.4.2
    - torch==1.3.1
    - torch-two-sample==0.1
    - torchfile==0.1.0
    - torchnet==0.0.4
    - tornado==6.0.3
    - tqdm==4.42.1
    - traitlets==4.3.3
    - transformers==2.3.0
    - urllib3==1.25.7
    - urwid==2.0.1
    - virtualenv==16.1.0
    - visdom==0.1.8.8
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - websocket-client==0.56.0
    - wrapt==1.11.2
    - yacs==0.1.6
    - yarg==0.1.9
    - zipp==0.6.0
prefix: /home/nicola/anaconda3/envs/teran